# Generated by Django 2.2.6 on 2020-05-27 06:23

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
