# Generated by Django 2.2.6 on 2020-05-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='resolve',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
