# Generated by Django 2.2.6 on 2020-05-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200530_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unique_id',
        ),
    ]
