# Generated by Django 2.2.6 on 2020-05-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
