# Generated by Django 2.2.6 on 2020-05-24 04:57

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200522_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
